### PR TITLE
filter out owl:Thing from closure map

### PR DESCRIPTION
**Pull request by cmungall**
Fixes https://github.com/geneontology/amigo/issues/395

### CODE REVIEW

**Comment by cmungall** [comment]
@kltm - the junit tests are not comprehensive for the solr loader, do we have a way to test?

**Comment by kltm** [comment]
Besides building it and running it against the AmiGO unit tests (which only have minimal numbers coverage), not at this time.

**Comment by kltm** [comment]
Not a lot of options here, unless you want to add unit tests against the JSON output; we'd just need to build and test against AmiGO.

**Comment by cmungall** [comment]
On 18 Oct 2016, at 16:05, kltm wrote:

> Not a lot of options here, unless you want to add unit tests against 
> the JSON output

That would be perfect

**Comment by fbastian** [comment]
Hmm 

`.filter(x -> x.getSignature().contains(owlThing)).filter(x -> x.getSignature().contains(owlThing))`

Aren't you keeping only `owlThing` here @cmungall? filter: "Returns a stream consisting of the elements of this stream that match the given predicate."

**Comment by cmungall** [comment]
good catch!! DO NOT MERGE!!!!

**Comment by cmungall** [comment]
OK, fixed that embarrassing error

**Comment by fbastian** [comment]
:p I was afraid of missing something.

**Pull request merged**
