### PR TITLE
Changing createNeighbors to omit redundant genus in equivalence axiom…

### PR DESCRIPTION
**Pull request by cmungall**
…, see https://github.com/geneontology/amigo/issues/360

### CODE REVIEW

**Comment by kltm** [comment]
@cmungall I'm still getting three parents for GO:1902401.

**Comment by cmungall** [comment]
Note that previously tests were failing, meaning `mvn clean install` 
wouldn't have made a new jar.

The tests were failing as they were overfitting for the case we now want 
to avoid. Fixed tests coming up as soon as I'm off BART...

**Comment by cmungall** [comment]
odd, https://github.com/owlcollab/owltools/pull/177/commits/2490d2c03a349f143a0b5de5fb943b4a44117fe3 *should* have failed.

**Comment by cmungall** [comment]
Add a test explicitly for 

```
[Term]
id: GO:1902401
name: detection of stimulus involved in mitotic DNA damage checkpoint
namespace: biological_process
def: "Any detection of stimulus that is involved in mitotic DNA damage checkpoint." [GOC:mtg_cell_cycle, GOC:TermGenie]
synonym: "perception of stimulus involved in mitotic DNA damage checkpoint" RELATED [GOC:TermGenie]
synonym: "stimulus detection involved in mitotic DNA damage checkpoint" EXACT [GOC:TermGenie]
synonym: "stimulus sensing involved in mitotic DNA damage checkpoint" RELATED [GOC:TermGenie]
is_a: GO:0072400 ! detection of stimulus involved in mitotic DNA integrity checkpoint
intersection_of: GO:0051606 ! detection of stimulus
intersection_of: part_of GO:0044773 ! mitotic DNA damage checkpoint
created_by: jl
creation_date: 2013-09-12T12:07:12Z
```

**Comment by kltm** [comment]
Are the tests now catching this?

**Comment by cmungall** [comment]
Yes: https://github.com/owlcollab/owltools/blob/46ba4782a5020513d2c58b10c62b2a1befa1dc17/OWLTools-Core/src/test/java/owltools/graph/OWLGraphWrapperEdgesAdvancedTest.java#L151

so the code is functioning as expected, and does not include the redundant genus term

**Comment by kltm** [comment]
So the test is passing (with a cut down ontology load?), but my loads still have the errant third edge? Hm.
Is there any way to prosecute owltools about where the edge is coming from on the cli?

**Comment by cmungall** [comment]
not sure what you mean about the cli query...

**Comment by kltm** [comment]
Just trying to find a way to test/probe it without having to load the full ontology set.

**Comment by cmungall** [comment]
I find it easiest to do ad-hoc tests using`--solr-url mock`, which will create a Mock solr loader (emits json)

**Pull request merged**
