### PR TITLE
Ensure OWLThing and OWLNothing are excluded from loads -

### PR DESCRIPTION
**Pull request by cmungall**
as both obejcts, and in topology graphs.

As a byproduct of this fix, we also have better mock testing for solr loading
Fixes https://github.com/geneontology/amigo/issues/428

### CODE REVIEW

**Comment by kltm** [comment]
Assuming the tests correctly capture the behavior, it looks correct tome.

**Comment by kltm** [comment]
Nice branch name.

**Comment by kltm** [comment]
@cmungall @balhoff Does minerva-cli.jar need to be rebuilt around this as well?

**Comment by cmungall** [comment]
No. Nothing is always 'there' in the OWL Model. It's only when exporting to a graph where there are a bunch of hidden assumptions about structure that problems arise.

**Pull request merged**
