### PR TITLE
Created a method that returns an OboGraph JSON string for any class or object prop 

### LINKED ISSUE #160: Extend golr loader to populate JSON blobs for ontology classes
Should be straightforward. 

add this to pom

``` xml
<dependency>
    <groupId>org.geneontology</groupId>
    <artifactId>obographs</artifactId>
    <version>${project.version}</version>
</dependency>
```

Call FromOwl.generateGraphDocument(OWLOntology) to get the object and use jackson to make the json

TBD: how does this related to the current bbop-graph population of fields? Extra field or subsume?
See https://github.com/geneontology/obographs for spec

### PR DESCRIPTION
**Pull request by cmungall**
Fixes #160

### CODE REVIEW

**Comment by cmungall** [comment]
ping @kltm

**Comment by kltm** [comment]
Were there tests for this one?

**Comment by cmungall** [comment]
https://github.com/owlcollab/owltools/blob/5aabc3de9795eb1098879f8c3773158733ede2d7/OWLTools-Core/src/test/java/owltools/graph/OWLGraphWrapperEdgesExtendedTest.java

But obviously the tests for the actual JSON structure itself live in the obographs java package

**Comment by kltm** [comment]
Okay, now looking at: https://github.com/geneontology/obographs/blob/master/examples/nucleus.json#L105
We'll either need to add labels for the `pred` or add more to the context (the latter is easier).
It's unfortunate that this and the minerva model (e.g. https://github.com/berkeleybop/bbop-graph-noctua/blob/master/tests/minerva-06.json) are going in different directions--it might be good to realign minerva/noctua (or whoever) at some point.

**Comment by cmungall** [comment]
Ship may have sailed on some of this, see for example https://github.com/geneontology/obographs/issues/3

**Comment by kltm** [comment]
Well, it may be easier to write a transform at my end for some of the stuff, but I think for our current use it won't be necessary. The Noctua client already does some of the transform to get it all into the bbop-graph subclass, but, IIRC, the structures are a little less rich at the end compared to what you have.

**Pull request merged**
