### PR TITLE
Fixed memory leaks that arise while generating solr index entries

### PR DESCRIPTION
**Pull request by yy20716**
This patch is for solving the memory leak issue that arises while generating solr indexes from go-cam model files. 
 - Problem: Loading each model file involves (i) retrieving some literal values from ontology objects and (ii) materializing implicit axioms. These literals and axioms are later directly referenced and fed into the object used for solr document objects. The problem is that, even if we put codes that remove ontology objects, garbage collectors in Java skipped releasing the literals and the axioms because they are still in use,  therefore all connected objects still stay in memory. 

 - Solution: I cloned new objects from reasoning and reasoner objects (and then dispose them once they are converted them as solr index entries).

 - I believe similar issues would arise for many other parts of owltools but I minimally fixed the codes to avoid any other potential bugs for now.

### CODE REVIEW

**Comment by kltm** [comment]
Great! What I'm going to do is fix up the dev machine (tomodachi) with the node updates and switch owltools over to this branch for testing.

**Comment by kltm** [comment]
Okay, so we have a chain of issues going back to how stale tomodachi is. I'll try and clean this up on Monday up the hill.

**Comment by kltm** [comment]
Updated on server for testing.
@yy20716 Could you look into the conflicts with master?

**Comment by yy20716** [comment]
FYI. I just wanted to note that it's not safe to merge this patch yet into the main branch, i.e. this one still uses the codes before [this pull request](
https://github.com/owlcollab/owltools/pull/249). Once we confirm that the codes in that pull request work as expected, I will then incorporate the codes from that request and make an additional commit into this branch. Thank you for your patience.

**Comment by kltm** [comment]
I've merged #249 into master.

**Comment by kltm** [comment]
@yy20716 How is the status now?
Tagging #212

**Comment by yy20716** [comment]
Seth (@kltm), I think it's now good to go but please let me know if you encounter any issues. I only tested this with dummy solr loader, so maybe there are something I couldn't consider before. Thank you for your time.

**Comment by kltm** [comment]
@yy20716 @cmungall 
As per our discussion, let's go ahead with this code and test in amigo 2.5.x/master to optimize the time we have with @yy20716 .

**Pull request merged**
